### ISSUE TITLE
can I get your hardware

### ISSUE THREAD

**Issue by seanXYZ** [KitSprout/KDWM1000#1]
I am very interesting about your programs, especially this one. But I am not an embedded engineer and do not know the hardware. So where I can get your hardware and development kits? Looking forward to your respond.

**Comment by hom-wang** [comment]
Sorry, those kits are design for my research, not for sale now. If one day available for sale it might only sale in Taiwan. You can connect local company or person to make one, the information you need all in Github. Thank you interesting about my programs and hope it will help you : )

**Comment by seanXYZ** [comment]
That's a  little pity. Thank you and good luck for your research!

**Comment by ZhengYuxiao** [comment]
@seanXYZ Hello, I want make own data set like VOC2007 Annotations, but the annotations is xml, I want generate yml,could you tell me how to generate the formats like follow
%YAML:1.0

annotation:
folder: VOC2007
filename: "000001.jpg"
source: {database: The VOC2007 Database, annotation: PASCAL VOC2007, image: flickr,
flickrid: '341012865'}
owner: {flickrid: Fried Camels, name: Jinky the Fruit Bat}
size: {width: '353', height: '500', depth: '3'}
segmented: '0'
object:

bndbox: {xmin: '48', ymin: '240', xmax: '195', ymax: '371'} name: dog pose: Left truncated: '1' difficult: '0'
bndbox: {xmin: '8', ymin: '12', xmax: '352', ymax: '498'} name: person pose: Left truncated: '1' difficult: '0'
