### ISSUE TITLE
Stuck at startup

### ISSUE THREAD

**Issue by ww9980** [KitSprout/KDWM1000#2]
Hi Hom,

I was compiling your code (`ApplicationSTD_serialPositioning`) and it went fine generating HEX file with no error. However, the program got stuck in the start up part and won't jump to main() (SWD JLink debugging the actual hardware). 

More specifically, the program runs til 

`LDR R0=_main`
**`BX R0`**

in `startup_stm32f411xe.s` and goes into an infinite loop. The disassembly shows infinite

`MOV R0,R0`.

BTW I used a different MCU (F411RE rather than CE), and the rest is identical. I looked up and found the startup code should be universal across any F411XE MCUs and the construction functions in the main program look fine. I am not sure what is causing the issue atm. 

Please give me a hint.

Thanks for help and 73,
ww9980

**Comment by hom-wang** [comment]
Hi ww9980,

I used Keil to compile and JLink debugger to download, there is no problem like this. I think there are two ways you can try:

1. check downloader setting is ok like memory address or chip ...
2. try more simple example like gpio.

Hope it helps :)
Hom

**Comment by ww9980** [comment]
Hi Hom,

Thanks for the tips. 

Yes, I have tried `KDWM_PeripheralSTD_GPIO` and it runs fine. 

I was using 0x20000000 til +0x0800 in RAM for algorithm option and 0x08000000 til 0x0807FFFH as programming algorithm since it's a 512KB RE version. 

It was very strange that I tried 2 different pieces of my board and one of them went past the startup code and ended up somewhere in DWM module config, however, the other one halted at startup. 

Has this ever happened to you? Is it because of an address mismatching or a hardware fault you reckon?

Much appreciated for your help,
9980

**Comment by hom-wang** [comment]
I didn't have this problem before and I'm sure the source code and setup file is fine for F411CE.
The problem is more likely in memory or hardware. Maybe you should recheck crystal if there is a hardware fault.

Hope it helps :)
Hom

**Comment by ww9980** [comment]
Hi Hom,

I am in the process of making a new board using F411CE. I'll put update here again regarding the startup code issue. Please reopen the topic. 

Thanks,
9980

**Comment by ww9980** [comment]
Hi Hom,

Could you please suggest what crystal should I use? What is your advice on the ppm? I presume that a higher ppm gives a higher accuracy? 

Thanks,
9980

**Comment by hom-wang** [comment]
Hi 9980

I use this crystal DSX221G. you can google it : )

Hom
