### ISSUE TITLE
问一下，这个图片是用什么软件画的

### ISSUE THREAD

**Issue by panrenjie** [KitSprout/KDWM1000#3]
https://camo.githubusercontent.com/aaaeefefd3b0f6fb3bb745264afcd04ec83b7513/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f556d5a6455537041584575793051624754502d78516e3762376e516e717334523446323761596c52456b5946463757795058616a583650334270333834356f30745438515343485f71644466484f734e514e3641444479794a74505653796663466a586834353571336548617735734534324459734b6a2d546131624e6f596977767630413143583379475f5853634f56487a2d4434772d5177504541446e656f57395745797956374363746d424e4a51394e5544755f5275526d63785a3978336c42504246583457524a31345f54475678475f74736a7736523668535478542d525062484f416146596b684c30687361316e755f4a737967724f6c61414e596c354a636c6a5577494d72794d796c6530637833594a6a2d505a58746c2d7556506c584e5a53614573564e334a6d74454b426c325a7069556f5f417143493134586638527032465775667277396b6f51426e55432d525361644e5f63706b38634f304b694d6c74523168684267416b7251734166374331744e42436e694b686a5a31344e766c796444383454706e6b3362354248325f4c52786b47434a7435546942564469354669785f4d6b53493879597958642d33446f346b374d624e6a5f39673641546b516b6e49664d7163374769316d6e6f5466686a314135735756595842346f414a7370555837414e52797a69417a5362766256304c56496e396958544850717644474f6661354838737a6171744263424e3867584330366831387474306c385941597666614934385647576e464d4d49756277434b4934526f51554f523568334567583178443266567a417141595445766241536565424572773d77313434302d683535372d6e6f

**Comment by hom-wang** [comment]
PowerPoint
